# Source: spacefx/templates/coresvc_fileserver.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    microsoft.azureorbital/serviceName: "app-python-shipdetector-onnx"
    microsoft.azureorbital/appName: "app-python-shipdetector-onnx"
  name: app-python-shipdetector-onnx-xfer-pv
  namespace: payload-app
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/spacedev/xfer/app-python-shipdetector-onnx
    type: DirectoryOrCreate
---
# Source: spacefx/templates/coresvc_fileserver.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    microsoft.azureorbital/serviceName: "app-python-shipdetector-onnx"
    microsoft.azureorbital/appName: "app-python-shipdetector-onnx"
  name: app-python-shipdetector-onnx-plugins-pv
  namespace: payload-app
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/spacedev/plugins/app-python-shipdetector-onnx
    type: DirectoryOrCreate
---
# Source: spacefx/templates/coresvc_fileserver.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-python-shipdetector-onnx-xfer-pvc
  namespace: payload-app
  labels:
    microsoft.azureorbital/serviceName: "app-python-shipdetector-onnx"
    microsoft.azureorbital/appName: "app-python-shipdetector-onnx"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
    limits:
      storage: 10G
  volumeName: app-python-shipdetector-onnx-xfer-pv
  storageClassName: local-path
---
# Source: spacefx/templates/coresvc_fileserver.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-python-shipdetector-onnx-plugins-pvc
  namespace: payload-app
  labels:
    microsoft.azureorbital/serviceName: "app-python-shipdetector-onnx"
    microsoft.azureorbital/appName: "app-python-shipdetector-onnx"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1M
    limits:
      storage: 10G
  volumeName: app-python-shipdetector-onnx-plugins-pv
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-shipdetector-onnx
  namespace: payload-app
  labels:
    app: app-python-shipdetector-onnx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python-shipdetector-onnx
  template:
    metadata:
      labels:
        app: app-python-shipdetector-onnx
        microsoft.azureorbital/appName: "app-python-shipdetector-onnx"
        microsoft.azureorbital/isDebugShim: "false"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app-python-shipdetector-onnx"
        dapr.io/app-protocol:   "grpc"
        dapr.io/app-port: "50051"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
    spec:
      runtimeClassName: nvidia
      containers:
      - name: app-python-shipdetector-onnx
        image: registry.spacefx.local:5000/app-python-shipdetector-onnx:0.11.0_debug-nightly
        imagePullPolicy: IfNotPresent
        env:
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "1"
        command: ["python"]
        args: ["/workspace/app-python-shipdetector-onnx/src/app/main.py"]